Map<String, dynamic> defaultLanguageMap = {
  "Title": "Dates' Health Recorder",
  "Config": "Application Settings",
  "LangConfig": "Language",
  "Theme": "Theme",
  "Account": "Account",
  "AccountExp":
      "SignIn is Recommended. If you SignIn, your record will be saved on the web cloud, and you can restore it when you reinstall this App or you change your device; if you don't, your record will be saved only on your device.",
  "EmailSignIn": "SignIn with E-mail",
  "EmailSignUp": "SignUp with E-mail",
  "GoogleSignIn": "SignIn with Google Account",
  "SignOut": "SignOut",
  "SignedIn": "You are Signed In.",
  "NotSignedIn": "You are NOT Signed In.",
  "Email": "Email Address",
  "Password": "Password",
  "Password2": "Input Password Again",
  "SignUp": "Sign UP",
  "SignIn": "Sign IN",
  "SignInFailed": "SignIn Attempt Failed!",
  "SignInSuccessful": "SignIn Successful!",
  "NoUser": "This E-mail is NOT registered.",
  "WrongPassword": "Password is Wrong.",
  "EmailInvalid": "E-mail is Invalid.",
  "EmailValid": "E-mail is Valid.",
  "PasswordInvalid": "Password is Invalid.",
  "PasswordValid": "Password is Valid.",
  "SignUpFailed": "SignUp Attempt Failed!",
  "SignUpSuccessful": "SignUp Successful!",
  "PasswordWeak": "Your password is too weak.",
  "AccountExists": "The account already exists for that email.",
  "UnexpectedError": "Unexpected Error happened. Your request failed.",
  "PasswordExp1": "Required: At least 6 characters.",
  "PasswordExp2": "Required: Include both letters(a-z,A-Z) and numbers(0-9).",
  "PasswordExp3":
      "Password can include: letters(a-z,A-Z), numbers(0-9), special characters(!?\$-_ etc.).",
  "Return": "Return",
  "Input": "Input Data",
  "CloudRecord": "Your Record will be saved on the web cloud.",
  "LocalRecord": "Your Record is saved only on your device.",
  "AddRecord": "Add Your Record",
  "Height": "Height",
  "Weight": "Weight",
  "NAVInput": "INPUT",
  "NAVRecord": "RECORD",
  "NAVAdviser": "ADVISER"
};
